/*
 * File:           SpritesHandler.java
 * Date:           January 4, 2015  11:18 AM
 *
 * @author  cuong.nguyen
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.atom.corex.assets.sprite;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 *
 * @author cuong.nguyen
 */
public interface SpritesHandler {

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_dir(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_dir() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_img(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_img() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_definitions(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_definitions() throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_spr(final Attributes meta) throws SAXException;
    
}
